### ISSUE TITLE
HitFinder GUI Improvement Recommendations

### ISSUE THREAD

**Issue by Leviathon2** [brandonhellman/mturk-suite#15]
I'd like to request that the GUI be returned to what it was prior to the worker site change. It was cleaner and easier to discern the difference between hits. I have definitely had a more difficult time seeing the hits since the change to hitscraper looking style. 

1) The text being underlined makes it harder for me to read, it's distracting.
2) There is virtually no padding or thick line around a hit that is part of the include list.
3) The text font could be changed to the old format (it was chunkier text - see image).
4) The colors when a link is clicked is not different enough to notice that well. I think this would be solved if the font stlye was changed though. 
5) Having the grey negative sign icon (check mark if you've done the hit before) in 2 columns is redundant. It should only be in either the Title or the Requester column. This saves valuable horizontal space.

Here is the older design for comparison:
https://i.imgur.com/XKxDi1o.png

**Comment by brandonhellman** [comment]
That design was dropped and will not be going back to it but the new version is easier to add display settings.

1. You're right, will be changed. 
2. They go to the include section, the bordering isn't as important and unlikely to change.
3. Plans to add a font size and weight options down the road so that will resolve this.
4. Using colored rows use the default link color changes. For non colored rows it will eventually be addressed further, but its has already been adjusted to be better seen once I can't use too much time for 3rd party themes. Probably easier to notice on bold as you said.
5. Requester match and title match for HIT Tracker, not redundant.

**Comment by brandonhellman** [comment]
https://github.com/Kadauchi/mturk-suite/projects/2#card-7019546
