### ISSUE TITLE
TO links delayed on MTurk Hits page

### ISSUE THREAD

**Issue by kimadagem** [brandonhellman/mturk-suite#187]
I don't usually accept a hit until I've at least discovered whether it has any reviews, but I can't do that now - the links are taking so long I could be almost finished with a shorter survey before the MTurk page is showing anything. This was a problem yesterday but it wasn't that noticeable; today, it is.

Hit Finder doesn't seem to have the same problem. For some reason I couldn't get it to find anything the first few times I tried, but when it finally did the links displayed right away.

**Comment by brandonhellman** [comment]
This is now happening because TO can't fail now, it will just keep retrying. Its more noticeable today because their servers are being slower to respond today. Before it would fail out and give you stale data. It doesn't seem to affect Finder because Finder keeps all of the review information in memory as its loaded so that old data will show until the new data come through. I can mimic this on the MTurk pages but it will require a decent amount of effort/time due to how review data is accessed there so this will have to wait a bit.

There is no real penalty for returning HITs. You'll lose out on far more HITs waiting to accept them than not being able to accept a HIT due to a requester using the deprecated return % qual.
