### ISSUE TITLE
Block list issues 

### ISSUE THREAD

**Issue by jlinab** [brandonhellman/mturk-suite#196]
HITS that I never blocked are being added to my block list. I'm not sure what is causing this to happen because they still show up in HIT finder, but when I go to the mturk homepage, ten or less hits are displayed and the rest are confined to my block list. I know that I couldn't have possibly blocked all of these requesters because many of them are ones I haven't even seen before.

**Comment by peddlerguy** [comment]
I've been experiencing this as well and after some investigating it looks like in my case the issue is due to  the "Block Location" option being selected

I thought that option would block all HITs that were available to any country except mine (Canada) but what it's doing is blocking the HIT if it's open to any country in ADDITION to Canada.

In  other words, if the HIT is only open to Canada, it isn't blocked - but if it's open to the U.S., or any other country, as well as Canada, it IS blocked
