### ISSUE TITLE
Turkopticon not showing up in queue. I do not want turkerview

### ISSUE THREAD

**Issue by jimsward** [brandonhellman/mturk-suite#209]
## Expected Behavior
Queue should have a link to turkopticon and turkopticon 2
## Current Behavior
Icon just gives turkerview. No longer gives turkopticon
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by Phrogster** [comment]
The same thing is happening for me except that I have Turkerview turned off. 
Mturk Suite v2.6.6
Google Chrome  Version 73.0.3683.75 (Official Build) (64-bit)
Windows 10 desktop

**Comment by Scottyc2112** [comment]
Happening with me too....

**Comment by brandonhellman** [comment]
A lot of people seem to be having issues today. Nothing in the extension has changed so its most likely just an issue with Turkopticon and their servers.

Does restarting your browser fix this issue (even if only temporarily)?

**Comment by Scottyc2112** [comment]
It didn't help with mine....I haven't been able to get it to work all day......but, wasnt Turkopticon suppose to quit permanently back on January 1st?

**Comment by Scottyc2112** [comment]
No, that didn't do anything.....Wasn't Turkopticon suppose to shut down back on Jan 1st anyway? ....I just like Turkopticon better than turkerview.
    On Thursday, March 14, 2019, 4:09:41 PM EDT, Brandon Hellman <notifications@github.com> wrote:  
 
 
A lot of people seem to be having issues today. Nothing in the extension has changed so its most likely just an issue with Turkopticon and their servers.

Does restarting your browser fix this issue (even if only temporarily)?

**Comment by Phrogster** [comment]
Restarting my browser did not help. I even updated my browser and restarted and that didn't help.

And Turkopticon changed their minds. The last I read, they are working to find funding and hope to keep TO open.

**Comment by WayotW** [comment]
Same issue. It does look like Turkopticon servers are having problems.

**Comment by brandonhellman** [comment]
Looks like this issue may be coming from Turkopticon 2 (https://turkopticon.info/) since I can't even access it at all. I'll need some additional information if possible to be sure it is this.

You can help confirm these suspicions for me by doing the below.

1. Go to chrome://extensions/
2. Turn on Developer mode on by clicking the toggle switch in the top right of the page on chrome://extensions/
3. Go to chrome://extensions/?id=iglbakfobmoijpbigmlfklckogbefnlf
4. Turn MTurk Suite off/on
5. Click the background page link under inspect views on chrome://extensions/?id=iglbakfobmoijpbigmlfklckogbefnlf to make the console log appear.
6. Open a new tab and go to https://worker.mturk.com/
7. Can you show me the console log popup that appears ( https://gyazo.com/55e6f70b782e7ea91c1b8f3beaf1459f ).

**Comment by auntgrammy** [comment]
![image](https://user-images.githubusercontent.com/29404959/54434131-e4c37700-4703-11e9-9129-eb41ef10948c.png)

**Comment by auntgrammy** [comment]
This was only part of it, but the first part. It kept generating. There were also a few "timed_out", but mainly refused.

**Comment by brandonhellman** [comment]
This should no longer be an issue after you get updated to v2.6.7.

**Comment by Phrogster** [comment]
Thank you! It is working now.
