### ISSUE TITLE
Brand new everything, fresh Win7 install, fresh Chrome, HitTracker not working.

### ISSUE THREAD

**Issue by AlienGit** [brandonhellman/mturk-suite#250]
Thanks for your hard work Kadauchi. New install to clean up things on this computer I've been using without problems. However, after fresh Win7 and fresh Chrome, newest version, for some reason, when I click on Sync, I get the popup, Syncing, Fetching Dashboard, and that's it. That stays up forever. The tab is frozen then. Cannot click cancel.

## Expected Behavior

I'd expect it to sync

## Current Behavior

It is not sync

## Possible Solution

Do I need to install something else with Chrome to get it to work? Do I need something in Windows, like .Net or some framework to get it to work?

## Steps to Reproduce (for bugs)

Click on MTS extension icon, CLick on HitTracker, Click on sync.

## Context

Can no longer sync.

## Your Environment

* Version used: 2.6.13
* Browser Name and version: Chrome Version 76.0.3809.100 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows 7, desktop

Hope you have an idea and it's a simple fix. Thanks!

**Comment by AlienGit** [comment]
Although I cannot use Firefox for turking, I tried the FF version of the extension, and it works properly, so I guess this means it's not a Windows or network issue?

**Comment by brandonhellman** [comment]
I don't know the root cause of this. There are quite a few other Issues that report the same problem and the fix ranges from reinstalling everything to it randomly started working again.

This is something that'll be fixed in the v3 rewrite that is coming in the next couple of months.

**Comment by AlienGit** [comment]
Well, I was hoping for something better than 'next couple of months'. We are talking livelihood.

Shouldn't there be a way to track this down? Seems like it should be a straightforward operation? Is there nothing to check to verify operation?

**Comment by BetaDude** [comment]
Alien, unfortunately, your issue is not one of 'if this--then do that'.  The author indicated this has been an issue with some folks, but each scenario and fix has been different, as each computer and configuration is different.  It's not 'straighforward' as it's not happening to everyone.....just some (but not all) people who seem to do re-installs.
Yes, you're using Chrome and Windows 7.  However, it could be various other things causing your problem... such as antivirus software, pop up blockers, etc..etc....
My suggestion is to first try completely uninstalling Chrome from your computer, restarting your computer, and then do a clean install of Chrome and start from there.  It just may fix your issue.
If not, check your pop-up blocker settings in Chrome,   The author is working on a new re-write of the software, which may fix the issue in the future.
Try and remember, also, you're using completely FREE software that the author is dedicating their own time on.

**Comment by JrRandy** [comment]
Since you said clean install, you did do all of your windows updates right?  Remember that Windows 7 is now 10 years old.  Alot of the original components/coding could have been made obsolete over the years.

**Comment by BetaDude** [comment]
Also very true indeed, Randy....since just about everything out there now is optimized for Windows 10....and there are issues with 'going backwards' between different programs.

**Comment by workbalance** [comment]
I've had similar problem and in my case helped reinstaling Chrome browser (Win10).
edit: after some time the issue come back, and I can't sync 'HIT tracker'
